name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.102' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies CouponsBot.Domain
      run: dotnet restore
      working-directory: CouponsBot.Domain
    - name: Install dependencies CouponsBot.Interfaces
      run: dotnet restore
      working-directory: CouponsBot.Interfaces
    - name: Install dependencies CouponsBot.Persistence
      run: dotnet restore
      working-directory: CouponsBot.Persistence
    - name: Install dependencies CouponsBot.Tests
      run: dotnet restore
      working-directory: CouponsBot.Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: CouponsBot.Tests
